/* SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef __DTS_NORD_IPCC_H
#define __DTS_NORD_IPCC_H

/* Physical client IDs */
#define IPCC_MPROC_AOP			0
#define IPCC_MPROC_TZ			1
#define IPCC_MPROC_ADSP0		2
#define IPCC_MPROC_NSP0			3
#define IPCC_MPROC_NSP1			4
#define IPCC_MPROC_NSP2			5
#define IPCC_MPROC_NSP3			6
#define IPCC_MPROC_APSS_NS0		7
#define IPCC_MPROC_APSS_NS1		8
#define IPCC_MPROC_APSS_NS2		9
#define IPCC_MPROC_APSS_NS3		10
#define IPCC_MPROC_ADSP1		11
#define IPCC_MPROC_ADSP2		12
#define IPCC_MPROC_APSS_NS4		13
#define IPCC_MPROC_SOCCP		15
#define IPCC_MPROC_CPUCP		16
#define IPCC_MPROC_A78CSS		17
#define IPCC_MPROC_TMESS		18
#define IPCC_MPROC_SAIL0		19
#define IPCC_MPROC_SAIL1		20
#define IPCC_MPROC_SAIL2		21
#define IPCC_MPROC_SAIL3		22
#define IPCC_MPROC_SAIL4		23
#define IPCC_MPROC_SAIL5		24

#define IPCC_COMPUTE_L0_ADSP0		0
#define IPCC_COMPUTE_L0_NSP0		1
#define IPCC_COMPUTE_L0_NSP1		2
#define IPCC_COMPUTE_L0_NSP2		3
#define IPCC_COMPUTE_L0_NSP3		4
#define IPCC_COMPUTE_L0_APSS_NS0	5
#define IPCC_COMPUTE_L0_GPU0		6
#define IPCC_COMPUTE_L0_APSS_NS1	7
#define IPCC_COMPUTE_L0_APSS_NS2	8
#define IPCC_COMPUTE_L0_APSS_NS3	9
#define IPCC_COMPUTE_L0_CVP		10
#define IPCC_COMPUTE_L0_ICP0		11
#define IPCC_COMPUTE_L0_ICP1		12
#define IPCC_COMPUTE_L0_VPU		13
#define IPCC_COMPUTE_L0_DPU0		14
#define IPCC_COMPUTE_L0_DPU1		15
#define IPCC_COMPUTE_L0_ADSP1		16
#define IPCC_COMPUTE_L0_ADSP2		17
#define IPCC_COMPUTE_L0_APSS_NS4	18
#define IPCC_COMPUTE_L0_SOCCP		20
#define IPCC_COMPUTE_L0_SAIL0		21
#define IPCC_COMPUTE_L0_SAIL1		22
#define IPCC_COMPUTE_L0_SAIL2		23
#define IPCC_COMPUTE_L0_SAIL3		24
#define IPCC_COMPUTE_L0_SAIL4		25
#define IPCC_COMPUTE_L0_SAIL5		26
#define IPCC_COMPUTE_L0_IPA		27
#define IPCC_COMPUTE_L0_GPU1		28

#define IPCC_COMPUTE_L1_ADSP0		0
#define IPCC_COMPUTE_L1_NSP0		1
#define IPCC_COMPUTE_L1_NSP1		2
#define IPCC_COMPUTE_L1_NSP2		3
#define IPCC_COMPUTE_L1_NSP3		4
#define IPCC_COMPUTE_L1_APSS_NS0	5
#define IPCC_COMPUTE_L1_GPU0		6
#define IPCC_COMPUTE_L1_APSS_NS1	7
#define IPCC_COMPUTE_L1_APSS_NS2	8
#define IPCC_COMPUTE_L1_APSS_NS3	9
#define IPCC_COMPUTE_L1_CVP		10
#define IPCC_COMPUTE_L1_ICP0		11
#define IPCC_COMPUTE_L1_ICP1		12
#define IPCC_COMPUTE_L1_VPU		13
#define IPCC_COMPUTE_L1_DPU0		14
#define IPCC_COMPUTE_L1_DPU1		15
#define IPCC_COMPUTE_L1_ADSP1		16
#define IPCC_COMPUTE_L1_ADSP2		17
#define IPCC_COMPUTE_L1_APSS_NS4	18
#define IPCC_COMPUTE_L1_SOCCP		20
#define IPCC_COMPUTE_L1_SAIL0		21
#define IPCC_COMPUTE_L1_SAIL1		22
#define IPCC_COMPUTE_L1_SAIL2		23
#define IPCC_COMPUTE_L1_SAIL3		24
#define IPCC_COMPUTE_L1_SAIL4		25
#define IPCC_COMPUTE_L1_SAIL5		26
#define IPCC_COMPUTE_L1_IPA		27
#define IPCC_COMPUTE_L1_GPU1		28

#define IPCC_PERIPH_ADSP0		0
#define IPCC_PERIPH_NSP0		1
#define IPCC_PERIPH_NSP1		2
#define IPCC_PERIPH_NSP2		3
#define IPCC_PERIPH_NSP3		4
#define IPCC_PERIPH_APSS_NS0		5
#define IPCC_PERIPH_PCIE0		6
#define IPCC_PERIPH_PCIE1		7
#define IPCC_PERIPH_APSS_NS1		8
#define IPCC_PERIPH_APSS_NS2		9
#define IPCC_PERIPH_APSS_NS3		10
#define IPCC_PERIPH_ADSP1		11
#define IPCC_PERIPH_ADSP2		12
#define IPCC_PERIPH_APSS_NS4		13

#define IPCC_FENCE_ADSP0		0
#define IPCC_FENCE_NSP0			1
#define IPCC_FENCE_NSP1			2
#define IPCC_FENCE_NSP2			3
#define IPCC_FENCE_NSP3			4
#define IPCC_FENCE_APSS_NS0		5
#define IPCC_FENCE_GPU0			6
#define IPCC_FENCE_APSS_NS1		7
#define IPCC_FENCE_APSS_NS2		8
#define IPCC_FENCE_APSS_NS3		9
#define IPCC_FENCE_CVP			10
#define IPCC_FENCE_ICP0			11
#define IPCC_FENCE_ICP1			12
#define IPCC_FENCE_CAM_ENG0		13
#define IPCC_FENCE_CAM_ENG1		14
#define IPCC_FENCE_CAM_ENG2		15
#define IPCC_FENCE_CAM_ENG3		16
#define IPCC_FENCE_CAM_ENG4		17
#define IPCC_FENCE_CAM_ENG5		18
#define IPCC_FENCE_CAM_ENG6		19
#define IPCC_FENCE_CAM_ENG7		20
#define IPCC_FENCE_CAM_ENG8		21
#define IPCC_FENCE_CAM_ENG9		22
#define IPCC_FENCE_CAM_ENG10		23
#define IPCC_FENCE_CAM_ENG11		24
#define IPCC_FENCE_CAM_ENG12		25
#define IPCC_FENCE_VPU			26
#define IPCC_FENCE_DPU0			27
#define IPCC_FENCE_DPU1			28
#define IPCC_FENCE_ADSP1		29
#define IPCC_FENCE_ADSP2		30
#define IPCC_FENCE_APSS_NS4		31
#define IPCC_FENCE_SOCCP		33
#define IPCC_FENCE_IPA			34
#define IPCC_FENCE_GPU1			35

#endif
